export const ABILTITY_SCORE_MIN = 8;
export const ABILTITY_SCORE_INIT = 27 + 6 * ABILTITY_SCORE_MIN;

export const HERO_NAMES = [
  'Elysia Seraphine',
  'Thalon Darkmore',
  'Lyra Silverwind',
  'Zephyr Stormrider',
  'Alistair Frostbane',
  'Isabella Nightshade',
  'Orion Emberheart',
  'Selene Moonshadow',
  'Darius Blackthorn',
  'Freya Ironspell',
  'Magnus Stormstrider',
  'Aurora Skyfire',
  'Cedric Shadowdancer',
  'Valeria Frostfang',
  'Lysander Thornbrook',
  'Seraphina Ravensong',
  'Lucius Bloodmoon',
  'Genevieve Starling',
  'Roderick Stormforge',
  'Elara Fireheart',
];

export const HERO_IMAGES = [
  './assets/ranger/0.jpg',
  './assets/ranger/1.jpg',
  './assets/ranger/2.jpg',
  './assets/ranger/3.jpg',
  './assets/ranger/4.jpg',
  './assets/ranger/5.jpg',
  './assets/ranger/6.jpg',
  './assets/ranger/7.jpg',

  './assets/warrior/0.jpg',
  './assets/warrior/1.jpg',
  './assets/warrior/2.jpg',
  './assets/warrior/3.jpg',
  './assets/warrior/4.jpg',
  './assets/warrior/5.jpg',
  './assets/warrior/6.jpg',
  './assets/warrior/7.jpg',
  './assets/warrior/8.jpg',

  './assets/wizard/0.jpg',
  './assets/wizard/1.jpg',
  './assets/wizard/2.jpg',
  './assets/wizard/3.jpg',
  './assets/wizard/4.jpg',
  './assets/wizard/5.jpg',
  './assets/wizard/6.jpg',
  './assets/wizard/7.jpg',
];
